version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Row90bit_20041803-2022-2026
      MYSQL_DATABASE: main_db
      MYSQL_USER: digeon
      MYSQL_PASSWORD: Row90bit_20041803-2022-2026   # same as DB_PASS
    volumes:
      - db_data:/var/lib/mysql
      # optional init file if you want to create marketplace_db too:
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pRow90bit_20041803-2022-2026 --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: digeon
      DB_PASS: Row90bit_20041803-2022-2026   # matches MYSQL_PASSWORD above
      DB_NAME: main_db
      DB_MKT_NAME: marketplace_db
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
